name: 'Auto Release'

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build & Upload Executable
    runs-on: windows-latest
    permissions:
      contents: write # Needed to upload assets to releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install Root Dependencies
        run: npm install

      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Executable
        run: .\build_exe.ps1
        shell: powershell

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          files: bluemine.exe
          fail_on_unmatched_files: true
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
